---
title: "Covid-19 lockdown measures and GDP growth"
output: html_notebook
---

# Housekeeping & packages

```{r}
rm(list = ls())
cat("\014")
options(scipen = 999)
library(bundesbank)
library(rdbnomics)
library(dplyr)
library(lubridate)
library(ggplot2)
library(readr) # parse_double
library(ggrepel)
```

# GDP growth in Q1

## DBnomics

### Eurostat

```{r}

codes_eurostat <- c("DE",
                    "BE",
                    "FR",
                    "IT",
                    "ES",
                    "IE",
                    "AT",
                    "DK",
                    "EL",
                    "FI",
                    "HU",
                    "CZ",
                    "PL",
                    "PT",
                    "SE",
                    "NL",
                    "SI")

countries_eurostat <- c("Germany",
                        "Belgium",
                        "France",
                        "Italy",
                        "Spain",
                        "Ireland",
                        "Austria",
                        "Denmark",
                        "Greece",
                        "Finland",
                        "Hungary",
                        "Czech Republic",
                        "Poland",
                        "Portugal",
                        "Sweden",
                        "Netherlands",
                        "Slovenia")

# initialize empty dataframe
df <- data.frame()

for (i in seq(1, length(codes_eurostat)))
{
  
    rdb(provider_code = paste0("Eurostat/teina011/Q.B1GQ.PCH_Q1_SCA.", codes_eurostat[i])) %>%
                        filter(original_period == "2020-Q1") %>%
                        mutate(original_value = parse_double(original_value)) %>%
                        select(original_value, `Geopolitical entity (reporting)`) -> tmp2

    df <- rbind(df, data.frame(gdpQ1 = tmp2$original_value, country = countries_eurostat[i]))
}
```

### OECD

```{r}
codes_oecd <- c("AUS",
                "BRA",
                "CAN",
                "CHL",
                "COL",
                "IND",
                "IDN",
                "ISR",
                "JPN",
                "KOR",
                "MEX",
                "GBR",
                "USA",
                "TUR",
                "CHE")

countries_oecd <- c("Australia",
                    "Brazil",
                    "Canada",
                    "Chile",
                    "Colombia",
                    "India",
                    "Indonesia",
                    "Israel",
                    "Japan",
                    "South Korea",
                    "Mexico",
                    "United Kingdom",
                    "United States",
                    "Turkey",
                    "Switzerland")

for (i in seq(1, length(codes_oecd)))
{
  
    rdb(provider_code = paste0("OECD/MEI/", codes_oecd[i], ".NAEXKP01.GPSA.Q")) %>%
                        filter(original_period == "2020-Q1") %>%
                        mutate(original_value = parse_double(original_value)) %>%
                        select(original_value, Country) -> tmp2

    df <- rbind(df, data.frame(gdpQ1 = tmp2$original_value, country = countries_oecd[i]))
}
```

## Bundesbank


```{r}
codes_Bbk <- c("BBXN1.Q.CN.S.NAG.B1QG00.0000.Z0N.PER.I00",
               "BBXN1.Q.RU00.S.NAG.B1QG00.0000.Z0N.CPC.I00")

countries_Bbk <- c("China", "Russia")

for (i in seq(1, length(codes_Bbk)))
{
  if (countries_Bbk[i] == "China") # China already in q/q growth rate!
  {
      tmp <- getSeries(codes_Bbk[i], start = "2020-01", end = "2020-03")



      df <- rbind(df, data.frame(gdpQ1 = tmp[1, 2],
                             country = countries_Bbk[i]))

}
  else
  {
      tmp <- getSeries(codes_Bbk[i], start = "2019-09", end = "2020-03")
      #tmp$values <- parse_double(tmp$values)

      df <- rbind(df, data.frame(gdpQ1 = round(tmp[2, 2] / tmp[1, 2] * 100 - 100, digits = 1),
                                 country = countries_Bbk[i]))
  }
}
```


# Stringency index

## Load raw data and select the relevant indicators

```{r}
rawdata_string <- read.csv("https://github.com/OxCGRT/covid-policy-tracker/raw/master/data/OxCGRT_latest.csv")


df_string <- rawdata_string %>% 
             mutate(Date = ymd(Date)) %>% 
             select(CountryName, ConfirmedDeaths, StringencyIndex, Date) 
```

## Calculate average index value for 2020Q1

```{r}
df_string_avgQ1 <- df_string %>% 
                   filter(Date <= "2020-03-31") %>%
                   group_by(CountryName) %>%
                   summarise(avgQ1 = mean(StringencyIndex))
```

## Calculate average index for 2020Q2

```{r}
df_string_avgQ2 <- df_string %>% 
                   filter(Date > "2020-03-31" & Date <= "2020-06-30") %>%
                   group_by(CountryName) %>%
                   summarise(avgQ2 = mean(StringencyIndex, na.rm = TRUE))
```


## Merge the two averages and calc diff

```{r}
merge(df_string_avgQ1, df_string_avgQ2, by = "CountryName") %>% mutate(diffQ2Q1 = avgQ2 - avgQ1) -> df_string_avg
```

# Analysis

## Merge two datasets

```{r}
df <- merge(df, df_string_avg, by.x = "country", by.y = "CountryName")
```


## Plot

```{r}

ggplot(data = df, aes(x = avgQ1, y = gdpQ1))+
  geom_point()+
  geom_point(data = filter(df, country %in%  c("Italy", "China", "Sweden", "South Korea", "Germany")),
                   aes(x = avgQ1, y = gdpQ1), color = "red")+
  geom_label(data = filter(df, country %in%  c("Italy", "China", "Sweden", "South Korea")),
                   aes(label = country),
                   nudge_x = 1.5, nudge_y = 0.7, size = 3)+
    geom_label(data = filter(df, country %in%  c("Germany")),
                   aes(label = country),
                   nudge_x = 3.0, nudge_y = -0.5, size = 3)+
  scale_x_continuous(breaks = seq(0, 60, 10))+
  labs(x = "index",
       y = "percent",
       title = "Lockdown measures and economic activity",
       subtitle = "Average stringency index vs. q/q GDP growth in the first quarter of 2020",
       caption = "Data for 35 advanced and emerging economies.\n Stringency index:higher values indicate more stringent lockdown measures, GDP: seasonally and calendar adjusted. \n Source: Hale, Thomas, Sam Webster, Anna Petherick, Toby Phillips and Beatriz Kira (2020);\n Eurostat, OECD, national statistical authorities.")
```


## Regression & prediction of Q2 GDP

```{r, fig.height = 5, fig.width = 5}
df_estim <- select(df, c("country","gdpQ1", "avgQ1")) %>% mutate(index = avgQ1) %>% select(-avgQ1)
df_fore <- select(df, c("country","gdpQ1", "diffQ2Q1")) %>% mutate(index = diffQ2Q1) %>% select(-diffQ2Q1)
m <- lm(gdpQ1 ~ index, df_estim)
summary(m)
df_fore$gdpQ2 <- predict(m, df_fore)

ggplot(df_fore, aes(x =fct_reorder(country, gdpQ2), y =gdpQ2))+
  geom_col(width = 0.7, color = "blue", fill = "blue")+ 
  coord_flip()+ labs(x= "", y = "%", title = "GDP growth forecasts for Q2", subtitle= "based on change in stringency index")+theme_minimal()
```


